server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: '*'


#ssl:
#key-store: file:///path/to/mykeys.jks
#key-store-password:
#key-password:

#logging:
#  file:
#    path: /logs/demo.log
#  level:
#    root: INFO

