server:
  port: 80
  #ssl:
  #key-store: file:///path/to/mykeys.jks
  #key-store-password:
  #key-password:

logging:
  file:
    path: /logs/demo.log
  level:
    root: INFO
#spring:
#  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql://localhost/readinglist
#      username: user
#      password: pwd
#      # data-source-class-name: com.mysql.jdbc.Driver

